# Generated by Django 3.2 on 2021-04-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_medicine_medicinecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('street_num', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
    ]
