# Generated by Django 3.2 on 2021-04-24 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210424_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pharmancy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pharmancy'),
        ),
    ]
