# Generated by Django 3.2 on 2021-04-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employee_pharmancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pharmancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pharmancy'),
        ),
    ]
