# Generated by Django 3.2 on 2021-04-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210424_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmancy',
            name='street_num',
            field=models.IntegerField(null=True),
        ),
    ]
