# Generated by Django 3.2 on 2021-04-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pharmancy_street_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmancy',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pharmancy',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pharmancy',
            name='street',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
