# Generated by Django 3.2 on 2021-04-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210425_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
