# Generated by Django 3.2 on 2021-04-25 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_alter_order_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacistOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('medicines', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medicine')),
                ('pharmancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pharmancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
