# Generated by Django 3.2 on 2021-04-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210425_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistorder',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
