# Generated by Django 3.2 on 2021-04-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_pharmacistorder_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistorder',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
