# Generated by Django 3.2 on 2021-04-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210426_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistorder',
            name='order_status',
            field=models.CharField(choices=[('OP', 'On Process'), ('OD', 'On Delivery'), ('DE', 'Delivered')], default='OP', max_length=2),
        ),
    ]
