# Generated by Django 3.2 on 2021-04-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_pharmacistorder_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pharmancy',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='pharmacistorder',
            old_name='pharmancy',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='employee',
            name='domain',
            field=models.CharField(choices=[('PH', 'Pharmacist'), ('SP', 'Supplier'), ('CU', 'Customer')], default='PH', max_length=2),
        ),
    ]
