# Generated by Django 3.2 on 2021-05-01 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_medicine_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
