# Generated by Django 3.2 on 2021-06-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210601_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
    ]
